version: "2"
linters:
  default: standard
  enable:
    - gocognit
    - gocritic
    - gocyclo
    - gosec
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gocognit
          - gocyclo
          - gosec

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$