name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Go Test
        run: go test ./...

      - name: Go Build
        run: |
          VERSION=$(git describe --tags --always --dirty)
          go build -ldflags "-X main.version=$VERSION" -v ./cmd/...
